using NHS111.Web.Functional.Utils;
using NHS111.Web.Functional.Utils.ScreenShot;
using NUnit.Framework;
using OpenQA.Selenium;

namespace NHS111.Web.Functional.Tests
{
    public class CategoryPageAgeGenderTests : BaseTests
    {
        [Test]
        [ScreenShotComparison]
        //alias and id check for categories age 5 Female with mental health
        public void CategoriesPage_PresentForFemaleChild()
        {
            var categoryPage = TestScenerios.LaunchCategoryScenerio(Driver, TestScenerioSex.Female, 5);
            categoryPage.VerifyPathwayInCategoryList("Stroke", "PA171FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Genital injury with cut or wound", "PW1010FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Palpitations", "PW1029FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Swallowed or breathed in an object", "PW1034FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Cold or flu", "PW1041FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Sinusitis", "PW1050FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Tiredness", "PW1071FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Bottom pain, swelling lump or itch", "PW1091FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Something in the eye", "PW1098FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Vaginal lump or swelling", "PW1103FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Breastfeeding problems", "PW1114FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Genital injury", "PW1116FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Shoulder problems", "PW1141FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Constipation", "PW1161FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Swollen or painful arm", "PW1165FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Leg injury with a cut or wound", "PW1234FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Splinters or problems with piercings", "PW1259FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Hand or wrist injury with a cut or wound", "PW1260FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Finger or thumb injury with a cut or wound", "PW1264FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Hand or wrist injury", "PW1267FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Finger or thumb injury", "PW1270FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Toe injury", "PW1282FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Glue on the skin", "PW1301FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Mouth ulcers", "PW1323FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Difficulty swallowing", "PW1496FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Ankle or foot injury", "PW1512FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Ankle or foot injury with a cut or wound", "PW1518FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Toe injury with a cut or wound", "PW1526FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Something in the ear", "PW1528FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Something stuck in the nose", "PW1529FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Something stuck in the bottom", "PW1531FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Something stuck in the vagina", "PW1532FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Self-harm or overdose", "PW1543FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Swollen or painful face or neck", "PW1548FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Drunk too much alcohol", "PW1552FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Diarrhoea and vomiting", "PW1554FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Itchy vagina", "PW1560FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Catheter problems", "PW1567FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Fingernail injury", "PW1570FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Bites or stings", "PW1575FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Cuts, scratches or grazes", "PW1590FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Leg injury", "PW1591FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Toenail injury", "PW1593FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Lower back injury", "PW1596FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Breast problems", "PW1605FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Toothache, swelling and other dental problems", "PW1611FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Swollen or painful hand, finger or wrist", "PW1616FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Blisters", "PW1625FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Eye or eyelid problems", "PW1628FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Coughing up blood", "PW1652FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Late or missed period", "PW1676FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Hair falling out or thinning", "PW1678FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Numbness or unusual sensation", "PW1683FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Sleep problems", "PW1697FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Sexual or period problems", "PW1699FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Fluid or wax coming from the ear with no loss of hearing", "PW1702FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Problems with wounds, plaster casts or metal rods", "PW1709FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Locked or aching jaw", "PW1712FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Nosebleed after an injury", "PW1713FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Stoma problems", "PW1719FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Cold arm or arm changing colour", "PW1733FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Cold leg or leg changing colour", "PW1734FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Diabetic blood sugar problems", "PW1746FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Behaving strangely", "PW1749FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Mental health", "PW1751FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Loss of bowel control", "PW1759FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Hearing problems or blocked ear", "PW1762FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Can't feel baby move as much", "PW1763FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Trembling or shaking", "PW1764FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Rashes, itchy skin, spots or blisters", "PW1772FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Hiccups", "PW1775FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Wound problems", "PW1776FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Stomach or side injury", "PW500FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Stomach or side injury with a cut or wound", "PW508FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Stomach ache or pain", "PW517FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Chest pain", "PA21FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Chemical burns", "PW564FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Toothache after an injury", "PW572FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Burns from heat", "PW580FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Chest or upper back injury without a cut or wound", "PW588FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Chest or upper back injury with a cut or wound", "PW596FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Dental injuries", "PW620FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Diarrhoea", "PW629FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Dizziness", "PW637FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Problems with weeing (passing urine)", "PW645FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Earache", "PW656FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Eye injury", "PW660FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Eye injury with a cut", "PW668FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Head, face or neck injury", "PW684FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Head, face or neck injury with a cut or wound", "PW692FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Falling, fainting or passing out", "PW700FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Fever or high temperature", "PW709FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Pain in the side of the body", "PW717FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Groin pain or swelling", "PW729FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Headache or migraine", "PW753FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Swollen or painful legs, knees, ankles or feet", "PW775FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Lower back pain", "PW783FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Lower back injury with a cut or wound", "PW798FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Nosebleed", "PW819FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Bleeding from the bottom", "PW846FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Sore throat", "PW854FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Accidentally taking something harmful", "PW881FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Difficulty weeing", "PW886FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Arm or shoulder injury", "PW895FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Arm or shoulder injury with a cut or wound", "PW902FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Bleeding from the vagina", "PW911FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Discharge from the vagina", "PW916FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Vomiting or nausea", "PW937FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Blood in wee (urine)", "PW961FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Cough", "PW978FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Blocked or stuffy nose", "PW984FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Sunburn", "PW987FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Heatstroke", "PW998FemaleChild");
            categoryPage.VerifyPathwayInCategoryList("Breathing problems", "PW557FemaleChild");
            categoryPage.VerifyOtherProblems("PW1348");
            categoryPage.CompareAndVerify(categoryPage, "1");
            var questionInfoPage = categoryPage.SelectPathway("Something stuck in the bottom");
            questionInfoPage.ClickIUnderstand();
            Driver.FindElement(By.XPath("//input[@value = 'PW1531FemaleChild']"));
        }

        [Test]
        //alias and id check for categories age 40 female with mental health
        public void CategoriesPage_PresentForFemaleAdult()
        {
            var categoryPage = TestScenerios.LaunchCategoryScenerio(Driver, TestScenerioSex.Female, 40);

            categoryPage.VerifyPathwayInCategoryList("Genital injury with cut or wound", "PW1010FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Palpitations", "PW1028FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Swallowed or breathed in an object", "PW1034FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Cold or flu", "PW1040FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Sinusitis", "PW1046FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Tiredness", "PW1070FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Bottom pain, swelling lump or itch", "PW1091FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Something in the eye", "PW1098FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Vaginal lump or swelling", "PW1102FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Breastfeeding problems", "PW1114FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Genital injury", "PW1116FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Shoulder problems", "PW1140FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Constipation", "PW1158FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Swollen or painful arm", "PW1164FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Leg injury with a cut or wound", "PW1234FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Leg injury", "PW1240FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Splinters or problems with piercings", "PW1259FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Hand or wrist injury with a cut or wound", "PW1260FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Finger or thumb injury with a cut or wound", "PW1264FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Hand or wrist injury", "PW1267FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Finger or thumb injury", "PW1270FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Toe injury", "PW1282FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Glue on the skin", "PW1301FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Mouth ulcers", "PW1323FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Difficulty swallowing", "PW1496FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Ankle or foot injury", "PW1512FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Ankle or foot injury with a cut or wound", "PW1518FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Toe injury with a cut or wound", "PW1526FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Something in the ear", "PW1528FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Something stuck in the nose", "PW1529FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Something stuck in the bottom", "PW1531FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Something stuck in the vagina", "PW1532FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Self-harm or overdose", "PW1543FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Swollen or painful face or neck", "PW1544FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Drunk too much alcohol", "PW1551FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Diarrhoea and vomiting", "PW1553FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Itchy vagina", "PW1559FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Catheter problems", "PW1567FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Fingernail injury", "PW1570FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Bites or stings", "PW1575FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Cuts, scratches or grazes", "PW1590FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Toenail injury", "PW1593FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Breast problems", "PW1603FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Toothache, swelling and other dental problems", "PW1610FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Swollen or painful hand, finger or wrist", "PW1614FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Blisters", "PW1625FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Eye or eyelid problems", "PW1627FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Coughing up blood", "PW1651FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Late or missed period", "PW1676FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Hair falling out or thinning", "PW1678FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Numbness or unusual sensation", "PW1683FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Sexual or period problems", "PW1684FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Sleep problems", "PW1686FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Fluid or wax coming from the ear with no loss of hearing", "PW1702FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Problems with wounds, plaster casts or metal rods", "PW1709FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Locked or aching jaw", "PW1712FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Nosebleed after an injury", "PW1713FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Stoma problems", "PW1719FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Cold arm or arm changing colour", "PW1733FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Cold leg or leg changing colour", "PW1734FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Diabetic blood sugar problems", "PW1746FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Behaving strangely", "PW1749FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Mental health", "PW1751FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Loss of bowel control", "PW1759FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Hearing problems or blocked ear", "PW1762FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Can't feel baby move as much", "PW1763FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Trembling or shaking", "PW1764FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Rashes, itchy skin, spots or blisters", "PW1771FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Hiccups", "PW1775FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Wound problems", "PW1776FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Stomach or side injury", "PW500FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Stomach or side injury with a cut or wound", "PW508FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Stomach ache or pain", "PW516FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Chest pain", "PA21FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Chemical burns", "PW564FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Toothache after an injury", "PW572FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Burns from heat", "PW580FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Chest or upper back injury without a cut or wound", "PW588FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Chest or upper back injury with a cut or wound", "PW596FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Dental injuries", "PW620FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Diarrhoea", "PW628FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Dizziness", "PW636FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Problems with weeing (passing urine)", "PW644FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Earache", "PW655FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Eye injury", "PW660FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Eye injury with a cut", "PW668FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Head, face or neck injury", "PW684FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Head, face or neck injury with a cut or wound", "PW692FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Falling, fainting or passing out", "PW700FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Fever or high temperature", "PW708FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Pain in the side of the body", "PW716FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Groin pain or swelling", "PW728FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Headache or migraine", "PW752FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Swollen or painful legs, knees, ankles or feet", "PW774FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Lower back pain", "PW782FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Lower back injury", "PW790FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Lower back injury with a cut or wound", "PW798FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Nosebleed", "PW818FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Bleeding from the bottom", "PW846FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Sore throat", "PW854FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Accidentally taking something harmful", "PW881FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Difficulty weeing", "PW886FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Arm or shoulder injury", "PW894FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Arm or shoulder injury with a cut or wound", "PW902FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Bleeding from the vagina", "PW910FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Discharge from the vagina", "PW915FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Vomiting or nausea", "PW936FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Blood in wee (urine)", "PW961FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Cough", "PW975FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Blocked or stuffy nose", "PW981FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Sunburn", "PW987FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Heatstroke", "PW998FemaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Breathing problems", "PW556FemaleAdult");
            categoryPage.VerifyOtherProblems("PW1345");
            categoryPage.CompareAndVerify(categoryPage, "1");

            var questionInfoPage = categoryPage.SelectPathway("Something stuck in the bottom");
            questionInfoPage.ClickIUnderstand();
            Driver.FindElement(By.XPath("//input[@value = 'PW1531FemaleAdult']"));
        }

        [Test]
        //alias and id check for categories age 5 Male with mental health
        public void CategoriesPage_PresentForMaleChild()
        {
            var categoryPage = TestScenerios.LaunchCategoryScenerio(Driver, TestScenerioSex.Male, 5);

            categoryPage.VerifyPathwayInCategoryList("Stroke", "PA171MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Genital injury with cut or wound", "PW1012MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Palpitations", "PW1031MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Swallowed or breathed in an object", "PW1034MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Cold or flu", "PW1043MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Tiredness", "PW1073MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Bottom pain, swelling lump or itch", "PW1091MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Something in the eye", "PW1098MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Genital injury", "PW1118MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Shoulder problems", "PW1143MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Constipation", "PW1162MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Swollen or painful arm", "PW1167MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Leg injury with a cut or wound", "PW1234MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Hand or wrist injury with a cut or wound", "PW1260MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Finger or thumb injury with a cut or wound", "PW1264MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Hand or wrist injury", "PW1267MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Finger or thumb injury", "PW1270MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Toe injury", "PW1282MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Glue on the skin", "PW1301MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Mouth ulcers", "PW1323MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Difficulty swallowing", "PW1496MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Ankle or foot injury", "PW1512MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Ankle or foot injury with a cut or wound", "PW1518MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Toe injury with a cut or wound", "PW1526MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Something in the ear", "PW1528MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Something stuck in the nose", "PW1529MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Something stuck in or around the penis", "PW1530MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Something stuck in the bottom", "PW1531MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Self-harm or overdose", "PW1543MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Swollen or painful face or neck", "PW1549MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Drunk too much alcohol", "PW1552MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Diarrhoea and vomiting", "PW1556MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Penis, testicle or scrotum problems", "PW1565MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Catheter problems", "PW1567MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Fingernail injury", "PW1570MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Bites or stings", "PW1575MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Cuts, scratches or grazes", "PW1590MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Leg injury", "PW1591MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Toenail injury", "PW1593MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Lower back injury", "PW1597MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Sinusitis", "PW1602MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Breast problems", "PW1606MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Toothache, swelling and other dental problems", "PW1611MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Swollen or painful hand, finger or wrist", "PW1617MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Blisters", "PW1625MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Eye or eyelid problems", "PW1630MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Coughing up blood", "PW1654MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Hair falling out or thinning", "PW1678MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Numbness or unusual sensation", "PW1683MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Sleep problems", "PW1697MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Male sexual problems", "PW1698MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Fluid or wax coming from the ear with no loss of hearing", "PW1702MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Problems with wounds, plaster casts or metal rods", "PW1709MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Locked or aching jaw", "PW1712MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Nosebleed after an injury", "PW1713MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Stoma problems", "PW1719MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Cold arm or arm changing colour", "PW1733MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Cold leg or leg changing colour", "PW1734MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Diabetic blood sugar problems", "PW1746MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Behaving strangely", "PW1749MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Mental health", "PW1751MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Splinters or problems with piercings", "PW1754MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Loss of bowel control", "PW1759MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Hearing problems or blocked ear", "PW1762MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Trembling or shaking", "PW1764MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Rashes, itchy skin, spots or blisters", "PW1772MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Hiccups", "PW1775MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Wound problems", "PW1776MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Stomach or side injury", "PW503MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Stomach or side injury with a cut or wound", "PW511MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Stomach ache or pain", "PW520MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Chest pain", "PA21MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Chemical burns", "PW564MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Toothache after an injury", "PW572MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Burns from heat", "PW580MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Chest or upper back injury without a cut or wound", "PW588MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Chest or upper back injury with a cut or wound", "PW596MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Dental injuries", "PW620MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Diarrhoea", "PW632MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Dizziness", "PW640MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Problems with weeing (passing urine)", "PW648MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Earache", "PW656MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Eye injury", "PW660MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Eye injury with a cut", "PW668MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Head, face or neck injury", "PW684MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Head, face or neck injury with a cut or wound", "PW692MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Falling, fainting or passing out", "PW700MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Fever or high temperature", "PW712MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Pain in the side of the body", "PW720MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Groin pain or swelling", "PW732MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Headache or migraine", "PW756MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Swollen or painful legs, knees, ankles or feet", "PW778MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Lower back pain", "PW786MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Lower back injury with a cut or wound", "PW801MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Nosebleed", "PW819MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Bleeding from the bottom", "PW846MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Sore throat", "PW854MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Accidentally taking something harmful", "PW881MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Difficulty weeing", "PW886MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Arm or shoulder injury", "PW895MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Arm or shoulder injury with a cut or wound", "PW902MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Vomiting or nausea", "PW940MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Blood in wee (urine)", "PW962MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Cough", "PW979MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Blocked or stuffy nose", "PW984MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Sunburn", "PW987MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Heatstroke", "PW998MaleChild");
            categoryPage.VerifyPathwayInCategoryList("Breathing problems", "PW560MaleChild");
            categoryPage.VerifyOtherProblems("PW1349");
            categoryPage.CompareAndVerify(categoryPage, "1");

            var questionInfoPage = categoryPage.SelectPathway("Something stuck in the bottom");
            questionInfoPage.ClickIUnderstand();

            Driver.FindElement(By.XPath("//input[@value = 'PW1531MaleChild']"));
        }

        [Test]
        //alias and id check for categories age 40 Male with mental health
        public void CategoriesPage_PresentForMaleAdult()
        {
            var categoryPage = TestScenerios.LaunchCategoryScenerio(Driver, TestScenerioSex.Male, 40);

            categoryPage.VerifyPathwayInCategoryList("Genital injury with cut or wound", "PW1012MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Palpitations", "PW1030MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Swallowed or breathed in an object", "PW1034MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Cold or flu", "PW1042MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Sinusitis", "PW1048MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Tiredness", "PW1072MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Bottom pain, swelling lump or itch", "PW1091MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Something in the eye", "PW1098MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Genital injury", "PW1118MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Shoulder problems", "PW1140MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Constipation", "PW1159MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Swollen or painful arm", "PW1166MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Leg injury with a cut or wound", "PW1234MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Leg injury", "PW1241MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Hand or wrist injury with a cut or wound", "PW1260MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Finger or thumb injury with a cut or wound", "PW1264MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Hand or wrist injury", "PW1267MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Finger or thumb injury", "PW1270MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Toe injury", "PW1282MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Glue on the skin", "PW1301MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Mouth ulcers", "PW1323MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Difficulty swallowing", "PW1496MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Ankle or foot injury", "PW1512MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Ankle or foot injury with a cut or wound", "PW1518MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Toe injury with a cut or wound", "PW1526MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Something in the ear", "PW1528MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Something stuck in the nose", "PW1529MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Something stuck in or around the penis", "PW1530MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Something stuck in the bottom", "PW1531MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Self-harm or overdose", "PW1543MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Swollen or painful face or neck", "PW1545MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Drunk too much alcohol", "PW1551MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Diarrhoea and vomiting", "PW1555MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Penis, testicle or scrotum problems", "PW1564MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Catheter problems", "PW1567MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Fingernail injury", "PW1570MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Bites or stings", "PW1575MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Cuts, scratches or grazes", "PW1590MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Toenail injury", "PW1593MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Breast problems", "PW1604MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Toothache, swelling and other dental problems", "PW1610MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Swollen or painful hand, finger or wrist", "PW1615MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Blisters", "PW1625MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Eye or eyelid problems", "PW1629MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Coughing up blood", "PW1653MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Hair falling out or thinning", "PW1678MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Numbness or unusual sensation", "PW1683MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Male sexual problems", "PW1685MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Sleep problems", "PW1686MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Fluid or wax coming from the ear with no loss of hearing", "PW1702MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Problems with wounds, plaster casts or metal rods", "PW1709MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Locked or aching jaw", "PW1712MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Nosebleed after an injury", "PW1713MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Stoma problems", "PW1719MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Cold arm or arm changing colour", "PW1733MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Cold leg or leg changing colour", "PW1734MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Diabetic blood sugar problems", "PW1746MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Behaving strangely", "PW1749MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Mental health", "PW1751MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Splinters or problems with piercings", "PW1754MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Loss of bowel control", "PW1759MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Hearing problems or blocked ear", "PW1762MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Trembling or shaking", "PW1764MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Rashes, itchy skin, spots or blisters", "PW1771MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Hiccups", "PW1775MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Wound problems", "PW1776MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Stomach or side injury", "PW503MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Stomach or side injury with a cut or wound", "PW511MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Stomach ache or pain", "PW519MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Chest pain", "PA21MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Chemical burns", "PW564MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Toothache after an injury", "PW572MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Burns from heat", "PW580MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Chest or upper back injury without a cut or wound", "PW588MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Chest or upper back injury with a cut or wound", "PW596MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Dental injuries", "PW620MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Diarrhoea", "PW631MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Dizziness", "PW639MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Problems with weeing (passing urine)", "PW647MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Earache", "PW655MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Eye injury", "PW660MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Eye injury with a cut", "PW668MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Head, face or neck injury", "PW684MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Head, face or neck injury with a cut or wound", "PW692MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Falling, fainting or passing out", "PW700MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Fever or high temperature", "PW711MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Pain in the side of the body", "PW719MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Groin pain or swelling", "PW731MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Headache or migraine", "PW755MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Swollen or painful legs, knees, ankles or feet", "PW777MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Lower back pain", "PW785MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Lower back injury", "PW793MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Lower back injury with a cut or wound", "PW801MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Nosebleed", "PW818MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Bleeding from the bottom", "PW846MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Sore throat", "PW854MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Accidentally taking something harmful", "PW881MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Difficulty weeing", "PW886MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Arm or shoulder injury", "PW897MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Arm or shoulder injury with a cut or wound", "PW902MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Vomiting or nausea", "PW939MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Blood in wee (urine)", "PW962MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Cough", "PW976MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Blocked or stuffy nose", "PW981MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Sunburn", "PW987MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Heatstroke", "PW998MaleAdult");
            categoryPage.VerifyPathwayInCategoryList("Breathing problems", "PW559MaleAdult");
            categoryPage.VerifyOtherProblems("PW1346");
            categoryPage.CompareAndVerify(categoryPage, "1");

            var questionInfoPage = categoryPage.SelectPathway("Something stuck in the bottom");
            questionInfoPage.ClickIUnderstand();

            Driver.FindElement(By.XPath("//input[@value = 'PW1531MaleAdult']"));
        }
    }
}
